name: Test

on:
  push:
    branches:
    - master
#branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:
  
permissions:
  contents: read

jobs:
  test-push:
    name: Push
    uses: Omnimods/omnitests/.github/workflows/omnitest.yml@v1
    with:
      repository: ${{ github.repository }}
      ref: ${{ github.ref }}
    secrets: inherit
