name: Test

on:
    # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test-push:
    name: Push
    uses: Omnimods/omnitests/.github/workflows/omnitest.yml@main
    with:
      repository: ${{ github.repository }}
      #ref: ${{ github.sha }}
      ref: ${{ github.ref }}
      test_ref: main
    secrets: inherit
